name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  axe-dev-hub:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          api_key: ${{ secrets.AXE_DEV_HUB_API_KEY }}
          server_url: https://axe.dequelabs.com
      # - uses: dequelabs/axe-devhub-action@v1
      #   with:
      #     api_key: ${{ secrets.AXE_DEV_HUB_API_KEY }}
